# Change these first
owner: c1rus # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: hint.hollen.sk
    url: https://hint.hollen.sk/
  - name: www.dubravka.sk
    url: https://www.dubravka.sk/
  - name: www.priklady.eu
    url: https://www.priklady.eu/sk/Index.alej           
  - name: www.rosler.sk
    url: https://www.rosler.sk/
  - name: www.sizp.sk
    url: https://www.sizp.sk/
  - name: master.kabernet.sk
    url: https://master.kabernet.sk/
  - name: www.kabernet.sk
    url: https://www.kabernet.sk
  - name: www.idl.sk
    url: https://www.idl.sk
  - name: www.slovakiatech.sk
    url: https://www.slovakiatech.sk
  - name: easyestate.sk
    url: https://easyestate.sk
  - name: www.koucovaciaskola.sk
    url: https://www.koucovaciaskola.sk
  - name: www.horecaclub.sk
    url: https://www.horecaclub.sk
  - name: www.rackscale.sk
    url: https://www.rackscale.sk
  - name: www.natureland.sk
    url: https://www.natureland.sk
  - name: www.virtualsan.sk
    url: https://www.virtualsan.sk
  - name: www.optikafontana.sk
    url: https://www.optikafontana.sk
  - name: www.levare.sk
    url: https://www.levare.sk
  - name: www.bellavista.sk
    url: https://www.bellavista.sk
  - name: www.lepsilamac.sk
    url: https://www.lepsilamac.sk/co-robime
  - name: www.clc.sk
    url: https://www.clc.sk
  - name: www.pefc.sk
    url: https://www.pefc.sk
  - name: www.garancnyfond.sk
    url: https://www.garancnyfond.sk
  - name: www.amplia.sk
    url: https://www.amplia.sk
  - name: www.itvkurze.sk
    url: https://www.itvkurze.sk
  - name: www.lamac.sk
    url: https://www.lamac.sk
  - name: www.livinn.sk
    url: https://www.livinn.sk
  - name: www.widex-eshop.sk
    url: https://www.widex-eshop.sk/
  - name: www.starsforstars.eu
    url: https://www.starsforstars.eu/
  - name: www.baoffice.sk
    url: https://www.baoffice.sk/
  - name: www.rosler.sk
    url: https://www.rosler.sk/
  - name: www.zuriarchitecture.com
    url: https://www.zuriarchitecture.com/
  - name: easyestate.sk
    url: https://easyestate.sk/
  - name: alejtech.sk
    url: https://www.alejtech.sk/
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
